# R e Rstudio

**R** é um sistema para estatística e gráficos. É ele que que faz a mágica.

Para instalar o R, siga as instruções da página https://cran.r-project.org. Existem versões para todos os sistemas operacionais.

**Rstudio** é uma espécie de interface para usar o R, que contém também muitos recursos interessantes que não têm nada a ver com estatística e que valem à pena aprender (veja o capítulo \@ref(rmarkdown)
).

O Rstudio pode ser instalado a partir da página https://www.rstudio.com/products/rstudio/download. 

Rstudio é uma empresa com o mesmo nome do programa que desenvolve e que tem contribuído muito para o desenvolvimento e divulgação do R.

A empresa vem criando uma série de complementos para o R para facilitar o uso e estender as potendialidades do programa. 

Programas que fornecem um interface para outro programa são chamados de IDE (Integrated Development Environment). Ainda que existam outras IDEs no mercado há mais tempo, o Rstudio vem se firmando como um padrão em análise de dados.
